trigger:
  branches:
    include:
    - master
    - 'validate/*'
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/
    - .github/

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  #codecov_token: # Get a new one from https://codecov.io/
  #ci_feed: # Azure Artifacts feed name
  NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages

jobs:
- template: azure-pipelines/build.yml
