name: autocomplete

on:
  pull_request:
    types:
    - labeled
    - unlabeled
    - opened
    - reopened
  check_run:
    types:
    - completed
  check_suite:
    types:
    - completed
  status: {}
jobs:
  check_complete:
    runs-on: ubuntu-latest
    steps:
    - uses: aarnott/pr-autocomplete@setupWork
      name: Evaluate auto-complete
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
