name: autocomplete

on:
  push:
    branches:
      - main
      - validate/*
  pull_request:
    types:
    - labeled
    - unlabeled
    - opened
    - reopened
    - synchronize
  check_run:
    types:
    - completed
  check_suite:
    types:
    - completed
  status:
jobs:
  check_complete:
    runs-on: ubuntu-latest
    steps:
    - uses: aarnott/pr-autocomplete@removeLabelsExplore
      name: Evaluate auto-complete
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
